### PR TITLE
feat: updated account settings page with form

### PR DESCRIPTION
**Pull request by jadeallencook**
Added form inputs to the account settings page.

Screenshot 2023-03-01 at 1 26 31 AM

### CODE REVIEW

**Review by asbhaskar — CHANGES_REQUESTED** [review]
Looks good, just some design comments

**Review by astroplexic — CHANGES_REQUESTED** [review]
The duration of the 'save confirmation box' is not the same interval across each volunteer role checkbox

**Comment by jadeallencook** [comment]
> The duration of the 'save confirmation box' is not the same interval across each volunteer role checkbox

Good catch, should be GTG now!

**Review by astroplexic — APPROVED** [review]
Sweet! **LGTM**

**Review by astroplexic — APPROVED** [review]
Sweet! LGTM v2

**Review by astroplexic — APPROVED** [review]
Sweet! LGTM v3

**Review by asbhaskar — APPROVED** [review]

**Pull request merged**
