### PR TITLE
feat: display number of requests returned and added link to request uid

### PR DESCRIPTION
**Pull request by jadeallencook**
Screenshot 2023-07-03 at 1 32 53 AM

Screenshot 2023-07-03 at 1 31 54 AM

### CODE REVIEW

**Comment by jadeallencook** [comment]
Is anyone available to review this today? It's a pretty small change.

**Review by A1Liu — APPROVED** [review]
UX-wise it feels weird to have the link displayed as text separately from the clickable thing. Since the modal and page are very similar, maybe it'd be better to have an "open in fullscreen view" link instead?

**Comment by A1Liu** [comment]
^ Non-blocking nitpick, to be clear

**Comment by jadeallencook** [comment]
> UX-wise it feels weird to have the link displayed as text separately from the clickable thing. Since the modal and page are very similar, maybe it'd be better to have an "open in fullscreen view" link instead?

Totally, that was my thought too. Right now the volunteers are sharing the ID (instead of using the "copy link" at the bottom) with the reimbursement coordinators and they aren't able to view the requests. I'm hoping that we will eventually phase this out and add another stage for reimbursement. Check out the #feedback channel, there's a little more info there.

**Pull request merged**
