### PR TITLE
fix: added translations for the events page copy

### PR DESCRIPTION
**Pull request by A1Liu**
Added some snippet refactors + translations for the events page.

### CODE REVIEW

**Review by jadeallencook — CHANGES_REQUESTED** [review]
Please remove the backslashes in the middle of sentences on `snippets/events-page.ts`, and format the document using Prettier. Besides that, everything LGTM. 

Thanks for doing this!

**Comment by A1Liu** [comment]
Do you want me to remove the backslash-newlines and replace them with newlines, or just remove them, putting the copy on a single line?

**Comment by jadeallencook** [comment]
> Do you want me to remove the backslash-newlines and replace them with newlines, or just remove them, putting the copy on a single line?

They should be removed completely for responsiveness. 

Also, could you also open this up on a different branch? 

We use Husky to format branche names:
- `fix/branch-name`
- `feat/branch-name`

And commit messages:
- `fix: commit message`
- `feat: commit message `

This will allow you to push without doing a force push, and automatically format all documents.

**Comment by A1Liu** [comment]
OK closing so that I can use the different branch name in #70

**Pull request closed without merging**
