### PR TITLE
Feat/view request page

### PR DESCRIPTION
**Pull request by asbhaskar**

### CODE REVIEW

**Comment by jadeallencook** [comment]
This is looking really good!

I'm seeing this issue with the comments:
Screenshot 2023-02-12 at 2 45 08 AM

I'd also like all of this to be in a modal component like in the first example:
https://react-bootstrap.github.io/components/modal/

Could you move the "copy link" button next to the close button too and remove the tooltip? 

Please have it so the text in the button changes after you click it.

Thanks @asbhaskar !

**Comment by asbhaskar** [comment]
@jadeallencook Good catch on the weird comment margins. I just have one thing I'd like to clarify, for the 'Copy Link' button, when the user clicks it it'll change to something like 'Link Copied'. Should the button disable and reenable or the text change back after a certain period of time? I was trying to find a way give some sort of feedback on multiple clicks

**Comment by jadeallencook** [comment]
That's correct @asbhaskar, you can do something like this:

```jsx
const [copied, setCopied] = useState<boolean>(false);

const copyLink = (link: string): void => {
    // copy link logic
    setCopied(true);
}

useEffect(() => {
    if (copied) {
        setTimeout(() => setCopied(false), 2000);
    }
}, [copied]);

return (
    <Button disabled={copied} onClick={() => copyLink(id)}}>
        {copied ? 'Link Copied' : 'Copy Link'}
    </Button>
);
```

And put it in a `/CopyLink` directory within the request model to make it easier to refactor out if we decide to use it somewhere else later. Make it a styled component as well with a set width, that way the width doesn't change when the amount of text updates .

**Comment by asbhaskar** [comment]
I made the changes above and did as you suggested for the copylinkbutton and copied the logic for the tooltip and just made it a button instead. Only thing is that the size of the Copy link button and exit modal button are different, do you want to increase the padding on the exit button or alter the size of the copy link button (don't know if it'll be reused somewhere else). 

Code for the exit button looks like this: ```calc(var(--bs-modal-header-padding-y) * .7) calc(var(--bs-modal-header-padding-x) * .7)```

**Review by jadeallencook — APPROVED** [review]
Great job @asbhaskar, can you move the button to the modal footer so it sits to the left of the close button? After that it should be good to merge in!

**Pull request merged**
