### PR TITLE
feat: created a homepage

### PR DESCRIPTION
**Pull request by jadeallencook**
Created a simple homepage to provide visitors information about what we do:

Screenshot 2023-07-01 at 12 47 58 AM

### CODE REVIEW

**Comment by jadeallencook** [comment]
This pull request is RFR if anyone has a few minutes to look it over.

**Comment by jadeallencook** [comment]
Ping, this pull request is ready for review.

**Comment by astroplexic** [comment]
Approved

**Review by A1Liu — APPROVED** [review]
I think there's some extra `.DS_Store` files in there

**Pull request merged**
