### PR TITLE
feat: added driver status feature

### PR DESCRIPTION
**Pull request by jadeallencook**

### CODE REVIEW

**Review by claytonleonardcook — COMMENTED** [review]
Is there a Driver type in the types folder and one in the objects folder? Just to have it for the filtering that I'm doing?

**Comment by jadeallencook** [comment]
> Is there a Driver type in the types folder and one in the objects folder? Just to have it for the filtering that I'm doing?

We store the UID for the driver, otherwise it's an empty string `''`.

**Comment by asbhaskar** [comment]
LGTM, I'm guessing viewDriver will be a separate ticket with a separate request

**Comment by claytonleonardcook** [comment]
LGTM

**Pull request merged**
